server:
    port: 8080
spring:
    datasource:
        name: ddc-dev-super
        url: jdbc:mysql://10.23.138.172:13306/ddc_mt?serverTimezone=GMT%2B8&characterEncoding=utf-8
        username: ddc-dev-super
        password: oXsVaT}"=-#c
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    jackson:
          time-zone: GMT+8
    redis:
      host: 10.23.138.172
      port: 16379
      timeout: 10000
      password: Ddc@2018
      db: 0
      jedis:
        pool:
          max-active: 2000
          max-wait: 100000
          max-idle: 100
          min-idle: 10
logging:
  level:
    root: debug
  config: classpath:logging-config.xml
mybatis:
  mapper-locations: classpath:mapping/*.xml